USE ETL; 
 DROP TABLE IF EXISTS datos_covid_geo; 
 CREATE TABLE datos_covid_geo (FECHA_ACTUALIZACION VARCHAR(100), ID_REGISTRO VARCHAR(100), ORIGEN VARCHAR(100), SECTOR VARCHAR(100), ENTIDAD_UM VARCHAR(100), SEXO VARCHAR(100), ENTIDAD_NAC VARCHAR(100), ENTIDAD_RES VARCHAR(100), MUNICIPIO_RES VARCHAR(100), TIPO_PACIENTE VARCHAR(100), FECHA_INGRESO VARCHAR(100), FECHA_SINTOMAS VARCHAR(100), FECHA_DEF VARCHAR(100), INTUBADO VARCHAR(100), NEUMONIA VARCHAR(100), EDAD VARCHAR(100), NACIONALIDAD VARCHAR(100), EMBARAZO VARCHAR(100), HABLA_LENGUA_INDIG VARCHAR(100), INDIGENA VARCHAR(100), DIABETES VARCHAR(100), EPOC VARCHAR(100), ASMA VARCHAR(100), INMUSUPR VARCHAR(100), HIPERTENSION VARCHAR(100), OTRA_COM VARCHAR(100), CARDIOVASCULAR VARCHAR(100), OBESIDAD VARCHAR(100), RENAL_CRONICA VARCHAR(100), TABAQUISMO VARCHAR(100), OTRO_CASO VARCHAR(100), TOMA_MUESTRA_LAB VARCHAR(100), RESULTADO_LAB VARCHAR(100), TOMA_MUESTRA_ANTIGENO VARCHAR(100), RESULTADO_ANTIGENO VARCHAR(100), CLASIFICACION_FINAL VARCHAR(100), MIGRANTE VARCHAR(100), PAIS_NACIONALIDAD VARCHAR(100), PAIS_ORIGEN VARCHAR(100), UCI VARCHAR(100), NOMBRE_ENTIDAD_RES VARCHAR(100), NOMBRE_MUNICIPIO_RES VARCHAR(100)); 
 CREATE INDEX indices_covid ON  datos_covid_geo(NOMBRE_ENTIDAD_RES,NOMBRE_MUNICIPIO_RES); 
  LOAD DATA  INFILE '/var/lib/mysql/datos_covid_geo.csv'  
  INTO TABLE datos_covid_geo 
  FIELDS TERMINATED BY ','  
 OPTIONALLY ENCLOSED BY '"'  
 LINES TERMINATED BY '\n'  
 IGNORE 1 LINES; 

