USE ETL; 
 DROP TABLE IF EXISTS datos_covid_geo; 
 CREATE TABLE datos_covid_geo (FECHA_ACTUALIZACION VARCHAR(255), ID_REGISTRO VARCHAR(255), ORIGEN VARCHAR(255), SECTOR VARCHAR(255), ENTIDAD_UM VARCHAR(255), SEXO VARCHAR(255), ENTIDAD_NAC VARCHAR(255), ENTIDAD_RES VARCHAR(255), MUNICIPIO_RES VARCHAR(255), TIPO_PACIENTE VARCHAR(255), FECHA_INGRESO VARCHAR(255), FECHA_SINTOMAS VARCHAR(255), FECHA_DEF VARCHAR(255), INTUBADO VARCHAR(255), NEUMONIA VARCHAR(255), EDAD VARCHAR(255), NACIONALIDAD VARCHAR(255), EMBARAZO VARCHAR(255), HABLA_LENGUA_INDIG VARCHAR(255), INDIGENA VARCHAR(255), DIABETES VARCHAR(255), EPOC VARCHAR(255), ASMA VARCHAR(255), INMUSUPR VARCHAR(255), HIPERTENSION VARCHAR(255), OTRA_COM VARCHAR(255), CARDIOVASCULAR VARCHAR(255), OBESIDAD VARCHAR(255), RENAL_CRONICA VARCHAR(255), TABAQUISMO VARCHAR(255), OTRO_CASO VARCHAR(255), TOMA_MUESTRA_LAB VARCHAR(255), RESULTADO_LAB VARCHAR(255), TOMA_MUESTRA_ANTIGENO VARCHAR(255), RESULTADO_ANTIGENO VARCHAR(255), CLASIFICACION_FINAL VARCHAR(255), MIGRANTE VARCHAR(255), PAIS_NACIONALIDAD VARCHAR(255), PAIS_ORIGEN VARCHAR(255), UCI VARCHAR(255), NOMBRE_ENTIDAD_RES VARCHAR(255), NOMBRE_MUNICIPIO_RES VARCHAR(255), LONG_MUNICIPIO_RES VARCHAR(255), LATITUD_MUNICIPIO_RES VARCHAR(255)); 
 CREATE INDEX indices_covid ON  datos_covid_geo(NOMBRE_ENTIDAD_RES,NOMBRE_MUNICIPIO_RES); 
  LOAD DATA  INFILE '/var/lib/mysql/datos_covid_geo.csv'  
  INTO TABLE datos_covid_geo 
  FIELDS TERMINATED BY ','  
 OPTIONALLY ENCLOSED BY '"'  
 LINES TERMINATED BY '\n'  
 IGNORE 1 LINES; 

